security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: login

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            json_login:
                check_path: login
                username_path: login
                password_path: password

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/login-db, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/check-auth, roles: PUBLIC_ACCESS }
        - { path: ^/me-db, roles: PUBLIC_ACCESS }
        - { path: ^/logout-db, roles: PUBLIC_ACCESS }
        - { path: ^/debug-, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
