parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    App\EventListener\CorsListener:
        tags:
            - { name: kernel.event_listener, event: kernel.response }

    contacts:
        class: App\Class\Contacts
        arguments:
            - '@doctrine.dbal.default_connection'

    monolog.formatter.simple:
        class: Monolog\Formatter\LineFormatter
        arguments:
            $format: "[%%datetime%%] %%channel%%.%%level_name%%: %%message%%\n"
            $dateFormat: "Y-m-d H:i:s"
            $allowInlineLineBreaks: false
            $ignoreEmptyContextAndExtra: true

    App\Class\Mailer:
        arguments:
            $logger: '@monolog.logger.mailer'
