parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $projectDir: '%kernel.project_dir%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    App\EventListener\CorsListener:
        tags:
            - { name: kernel.event_listener, event: kernel.response }

    contacts:
        class: App\Class\Contacts
        arguments:
            - '@connection'

    entity.user:
        class: App\Class\Entity\User
        arguments:
            - '@connection'

    monolog.formatter.simple:
        class: Monolog\Formatter\LineFormatter
        arguments:
            $format: "[%%datetime%%] %%channel%%.%%level_name%%: %%message%%\n"
            $dateFormat: "Y-m-d H:i:s"
            $allowInlineLineBreaks: false
            $ignoreEmptyContextAndExtra: true

    App\Class\Mailer:
        arguments:
            $logger: '@monolog.logger.mailer'

    App\Class\Security\Auth:
        arguments:
            - '@connection'

    connection:
        class: App\Class\Core\DB\Connection
        arguments:
            - '@doctrine.dbal.default_connection'

    template_manager:
        class: App\Class\TemplateManager
        arguments:
            - '@filesystem'

    App\Filesystem:
        arguments:
            $projectDir: '%kernel.project_dir%'
